// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/** True si el .env tiene URL y anon key reales (evita pantalla en blanco por throw en import). */
export const isSupabaseConfigured = Boolean(
  typeof envUrl === 'string' && envUrl.trim() && typeof envKey === 'string' && envKey.trim()
);

// createClient(undefined, undefined) lanza en tiempo de import y React no monta.
const SUPABASE_URL = (typeof envUrl === 'string' && envUrl.trim()) || 'https://xxxxxxxxxxxxxx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  (typeof envKey === 'string' && envKey.trim()) || 'sb_publishable_placeholder_configure_env';

if (!isSupabaseConfigured && import.meta.env.DEV) {
  console.warn(
    '[MN Music] Falta VITE_SUPABASE_URL o VITE_SUPABASE_PUBLISHABLE_KEY en .env — la app arranca pero Supabase no funcionará hasta configurarlas.'
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});